### PR TITLE
CC-BY-NC-ND parts removed from project (#1)

### PR DESCRIPTION
**Pull request by karelmaxa**
Completely removed all CC-BY-NC-ND parts from project.

### CODE REVIEW

**Comment by Kortanul** [comment]
I'm holding off on this for now because I want to make sure we have documentation to replace what we're removing first. The CC-BY-ND doesn't affect us until we have to actually start modifying those docs.

**Comment by siepkes** [comment]
It might be a good idea to move it (unmodified) to a separate repo out of this one. We could add a clear disclaimer to that repo stating that we can't make changes to it.

**Comment by Kortanul** [comment]
@siepkes -- can you clarify? You mean, move the docs to a separate repo?

**Comment by pavelhoral** [comment]
We should just remove the documentation. We will still have it in sustaining branches. I don't see any point in having this kind of legacy baggage present in master.

**Comment by siepkes** [comment]
@Kortanul Yes that was the idea; Move the docs in to a separate repo and remove them here to "cleanse" the repo of licenses we can't work with. It might be confusing to have an OSS repo with parts which arent OSS.

**Comment by Kortanul** [comment]
@karelmaxa @pavelhoral Some of the samples and files being removed are CDDL, NOT CC-BY-ND. For that reason, I'm still not going to merge this. I need you guys to go back over this and remove just the content we don't have a license for.

For example, we should not need to remove the full stack sample or the getting started sample. The ReadMe files for some of the samples may be covered by CC-BY-ND, but if the content of the code files carries a CDDL header, it's CDDL.

**Comment by siepkes** [comment]
+1 We only need to get rid of the content we absolutely need to get rid of.

**Comment by pavelhoral** [comment]
I would like to remove more than less... we should build new samples from the scratch and leave legacy stuff elsewhere (e.g. a different project maybe).

**Comment by Kortanul** [comment]
I'm not merging this. This changes too much, and it takes away more than it adds. Please take on the project to provide new samples. Until then, the content stays.

**Pull request closed without merging**
