### PR TITLE
Issue #11 - Update link on object UID change

### PR DESCRIPTION
**Pull request by tbigby-kristin**
Hi team,

Issue #11 causes object links to be lost when the UID of the target object changes. I recently ran into this with my own project.

@GuyPaddock provided pull request #45 some years ago but there were a few unnecessary changes.

I needed to solve this issue so have attempted to re-implement Guy's work in a pull request with fewer changes. All credit goes to Guy for your work in finding the cause and coming up with both a test case and solution.

I hope this fix can be merged so that it is part of the WrenIDM project.

Many thanks, Tony

### CODE REVIEW

**Comment by pavelhoral** [comment]
We have cleaned Guy's PR as well in #106. However we were sitting on that since then. I will check both PRs again ASAP.

**Comment by tbigby-kristin** [comment]
Indeed, sorry I missed that before submitting mine. I have no problem if you want to merge #106 instead :)

**Comment by pavelhoral** [comment]
I have updated your PR and will merge it once the tests are green.

Btw this PR does not solve #11 completely. My original report was describing situation when the target object's ID changes out of the recon process. I.e. when OpenLDAP administrator mistakenly deletes an LDAP entry and then recreates it with a different entryUUID. But that is a bit more complex scenario to solve.

**Comment by tbigby-kristin** [comment]
Many thanks @pavelhoral !

Fair enough, a change to a target object's ID outside the reconciliation process would be much more difficult to solve, but this specific issue where the ID changes within the reconciliation process is what I needed to solve currently.

The ID change outside the recon process sounds to me like it would create a different 'Behaviour Situation' - 'Link Moved':

- Source links to a target object that doesn't exist, but a different target matches the correlation query

Then a new 'RELINK' action could be taken if configured in the mapping to drop the existing link and create a new link.

Anyway, just some thoughts. Thanks again for merging this fix!

**Pull request merged**
